### PR TITLE
Adding contributing.md file (Also added code_of_conduct.md file)

### PR DESCRIPTION
**Pull request by Nikhil0-3**
1. contributing.md file - 
As per the issue #168  I added the file with all require changes

added the following points-
Project Overview
How to Contribute
Contribution Guidelines
Opening a Pull Request
Issue Report Process
Technologies Used
Community and Communication
Project Structure
Inspiration for Contributions

2. code_of_conduct.md file -

How to contribute (fix bugs, add features)
Steps for submitting changes
Project setup instructions
Rules for code style
Code of conduct for respectful behavior
Enhance the project structure
Add the help and support section
Add the pull request section
Add issue report process section

Also , I tried to make ik more creative.
If any further changes required please tell me.

### CODE REVIEW

**Comment by Nikhil0-3** [comment]
I have added two files contributing.md and second one is code_of_conduct.md

If possible make this issue as level 2

Any further changes required please let me know.
Thank you for giving me an opportunity.

**Comment by Nikhil0-3** [comment]
If possible please make it as accepted for hactoberfest and also increase its level to level 2

**Comment by sanjay-kv** [comment]
Hi Nikhil, this is for practice only we cant simply add level to readme files, other contributor will flag u as spam and hacktoberfest wont accept simple PR

**Comment by Nikhil0-3** [comment]
> Hi Nikhil, this is for practice only we cant simply add level to readme files, other contributor will flag u as spam and hacktoberfest wont accept simple PR

Ok Sir , Thank you for information.

**Pull request merged**
