### PR TITLE
Create jency1 - unmerged PR's

### PR DESCRIPTION
**Pull request by jency1**
Total unmerged PR's :

1. Improved the UI of Amantran Food Ordering - (https://github.com/khushi-joshi-05/Food-ordering-website/pull/1613) - level 3
2. Improved the UI of Frosa - (https://github.com/khushi-joshi-05/Food-ordering-website/pull/1610) - level 2
3. Bug fixed - Fixed the footer - (https://github.com/khushi-joshi-05/Food-ordering-website/pull/1608) - level 2

1. Added coding platform - TopCoder in DSA - (https://github.com/jfmartinz/ResourceHub/pull/1583) - level 1
2. Added coding platform - codewars for DSA - (https://github.com/jfmartinz/ResourceHub/pull/1581) - level 1
3. Added resource for Interview Questions asked in DSA - (https://github.com/jfmartinz/ResourceHub/pull/1579) - level 1
4. Added Trie data structure in DSA - (https://github.com/jfmartinz/ResourceHub/pull/1577) - level 1
5. Added heap data structure in DSA - (https://github.com/jfmartinz/ResourceHub/pull/1575) - level 1
6. Added Hash Map data structure in DSA - (https://github.com/jfmartinz/ResourceHub/pull/1573) - level 1

1. Made Navbar Sticky - (https://github.com/CSEdgeOfficial/learn.csedge.courses/pull/486)

### CODE REVIEW

**Comment by jency1** [comment]
@sanjay-kv Please merge all this PR's by adding the level labels as soon as possible.

**Comment by sanjay-kv** [comment]
you have to raise mutiple pr here.

**Comment by jency1** [comment]
Ok. I will raise multiple PR's within 1 hour. Thanks for the information. @sanjay-kv

**Comment by jency1** [comment]
@sanjay-kv Please assign this PR to me. Else this won't be counted in the leaderboard as per the rules.

**Pull request merged**
