### PR TITLE
Open PR - Beautiify

### PR DESCRIPTION
**Pull request by hars-21**
https://github.com/Rakesh9100/Beautiify/pull/1366

Hi @sanjay-kv , This beautiify PR is not merged till now and PA is also not responding.
Please merge this PR.

### CODE REVIEW

**Comment by Rakesh9100** [comment]
PR is getting reviewed one by one and merged, remove the point label from here 

@sanjay-kv

**Comment by hars-21** [comment]
@Rakesh9100 Please can you do it asap. As the contribution period ends in 5mins.

**Comment by Rakesh9100** [comment]
It is already done, you can check @hars-21

**Comment by hars-21** [comment]
Ok

**Pull request merged**
