### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by saras-69**
please add level

### CODE REVIEW

**Comment by saras-69** [comment]
@sanjay-kv @samarasimhapeyala  @zeeno2616  @Jisha-tr please assigned the level

**Comment by saras-69** [comment]
@sanjay-kv could you please assign level 3🥹

**Comment by saras-69** [comment]
@sanjay-kv I’m really close to earning the badge, and this would help me reach it. I’d be so grateful if you could do me this favor! .... please

**Comment by sanjay-kv** [comment]
HEy @saras-69 I appreciate that, but if i assign level3 for adding just name other contributor gonna make an issue. why dont you work on the readme files in this repo. https://github.com/recodehive/machine-learning-repos

**Pull request merged**
